# Generated by Django 6.0.7 on 2026-08-12 14:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "withdrawal_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.50"),
                        help_text="Flat fee in USDT charged for each TRON withdrawal.",
                        max_digits=10,
                    ),
                ),
                (
                    "min_usdt_withdrawal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Minimum allowed USDT withdrawal amount.",
                        max_digits=10,
                    ),
                ),
                (
                    "max_usdt_withdrawal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5000.00"),
                        help_text="Maximum allowed USDT withdrawal amount.",
                        max_digits=10,
                    ),
                ),
                (
                    "withdrawals_frozen",
                    models.BooleanField(
                        default=False,
                        help_text="Global switch to immediately freeze all external withdrawals.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Withdrawal Configuration",
                "verbose_name_plural": "Withdrawal Configuration",
            },
        ),
        migrations.CreateModel(
            name="Withdrawal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset", models.CharField(default="USDT", max_length=10)),
                ("network", models.CharField(default="TRON", max_length=20)),
                ("amount", models.DecimalField(decimal_places=6, max_digits=18)),
                ("fee", models.DecimalField(decimal_places=6, max_digits=18)),
                ("net_amount", models.DecimalField(decimal_places=6, max_digits=18)),
                ("destination_address", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("BROADCAST", "Broadcast"),
                            ("CONFIRMED", "Confirmed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=256,
                        null=True,
                        unique=True,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("blnk_transaction_refs", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("broadcast_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="withdrawals_user_id_add96e_idx"
                    )
                ],
            },
        ),
    ]
