# Generated by Django 6.0.7 on 2026-08-22 21:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("withdrawals", "0002_seed_users_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BscNonceTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("next_nonce", models.BigIntegerField(default=0)),
                ("last_reconciled_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="DepositRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_id",
                    models.CharField(db_index=True, max_length=256, unique=True),
                ),
                ("network", models.CharField(default="BSC", max_length=20)),
                ("asset", models.CharField(default="USDT", max_length=10)),
                ("tx_hash", models.CharField(db_index=True, max_length=256)),
                ("log_index", models.IntegerField(default=0)),
                ("from_address", models.CharField(max_length=128)),
                ("to_address", models.CharField(max_length=128)),
                ("amount", models.DecimalField(decimal_places=6, max_digits=18)),
                ("block_number", models.BigIntegerField()),
                ("confirmations", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CREDITED", "Credited"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "blnk_transaction_id",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WithdrawalNetworkConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("network", models.CharField(db_index=True, max_length=20)),
                (
                    "asset",
                    models.CharField(db_index=True, default="USDT", max_length=10),
                ),
                (
                    "withdrawal_fee",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.50"), max_digits=18
                    ),
                ),
                (
                    "min_withdrawal",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("10.00"), max_digits=18
                    ),
                ),
                (
                    "max_withdrawal",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("5000.00"), max_digits=18
                    ),
                ),
                ("withdrawals_enabled", models.BooleanField(default=True)),
                ("withdrawals_frozen", models.BooleanField(default=False)),
                ("confirmations_required", models.PositiveIntegerField(default=12)),
                (
                    "contract_address",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("decimals", models.PositiveIntegerField(default=18)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Withdrawal Network Configuration",
                "verbose_name_plural": "Withdrawal Network Configurations",
                "unique_together": {("network", "asset")},
            },
        ),
        migrations.CreateModel(
            name="WithdrawalAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=128)),
                ("network", models.CharField(max_length=20)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("verified", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "address", "network")},
            },
        ),
    ]
