# Generated by Django 6.0.7 on 2026-08-11 19:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_fee_amount_order_payment_method_order_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usdt_credited', models.DecimalField(decimal_places=6, max_digits=14)),
                ('mwk_received', models.DecimalField(decimal_places=2, max_digits=14)),
                ('blnk_transaction_refs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the locked rate / payment window expires.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default='', help_text='Short reference the user quotes in the mobile money narration.', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_transaction_id',
            field=models.CharField(blank=True, default='', help_text='Mobile money transaction ID supplied by the user.', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='received_mwk_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount the admin actually found on the mobile money statement.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('payment_submitted', 'Payment Submitted'), ('under_review', 'Under Review'), ('payment_mismatch', 'Payment Mismatch'), ('payment_verified', 'Payment Verified'), ('settling', 'Settling'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('awaiting_deposit', 'Awaiting Deposit'), ('cancelled', 'Cancelled')], default='awaiting_payment', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_transaction_id', ''), _negated=True), fields=('payment_transaction_id',), name='unique_payment_transaction_id'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('payment_reference', ''), _negated=True), fields=('payment_reference',), name='unique_payment_reference'),
        ),
        migrations.AddField(
            model_name='orderauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderauditlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordersettlement',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordersettlement',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to=settings.AUTH_USER_MODEL),
        ),
    ]
