"""
Django settings for Bitfuse project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path

from datetime import timedelta
from decouple import config, RepositoryEnv
import dj_database_url

TESTING = 'test' in sys.argv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

import warnings

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="change-me-later-bitfuse-secret-key-32bytes-min")
if len(SECRET_KEY) < 32:
    warnings.warn("SECRET_KEY is shorter than the recommended 32 bytes minimum length.", UserWarning)

JWT_SIGNING_KEY = config("JWT_SECRET_KEY", default=SECRET_KEY)
if len(JWT_SIGNING_KEY) < 32:
    warnings.warn("JWT_SECRET_KEY is shorter than the recommended 32 bytes minimum length.", UserWarning)

SIMPLE_JWT = {
    "SIGNING_KEY": JWT_SIGNING_KEY,
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}

# Session Inactivity & Lifetime Configuration
SESSION_INACTIVITY_TIMEOUT_MINUTES = config("SESSION_INACTIVITY_TIMEOUT_MINUTES", default=15, cast=int)
SESSION_MAX_LIFETIME_HOURS = config("SESSION_MAX_LIFETIME_HOURS", default=24, cast=int)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "storages",
    "accounts",
    "kyc",
    "orders",
    "withdrawals",
]

MIDDLEWARE = [

    
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Bitfuse.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Bitfuse.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.parse(
        config("DATABASE_URL")
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "accounts.authentication.CustomJWTAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "10000/minute" if TESTING else "30/minute",
        "user": "10000/minute" if TESTING else "120/minute",
        "auth": "10000/minute" if TESTING else "10/minute",
        "financial": "10000/minute" if TESTING else "20/minute",
    },
    "EXCEPTION_HANDLER": "Bitfuse.exceptions.custom_exception_handler",
}

BLNK_BASE_URL = config("BLNK_BASE_URL", default="https://bitfuse-blnk-server-qfn2.onrender.com")
BLNK_SECRET_KEY = config("BLNK_SECRET_KEY", default="")

CURRENCY_PRECISION = {
    "MWK": 100,     # 2 decimal places
    "USDT": 1_000_000,  # 6 decimal places
}

# Mobile money buy flow: how long a quoted rate stays valid once an order exists.
PAYMENT_WINDOW_MINUTES = config("PAYMENT_WINDOW_MINUTES", default=15, cast=int)

# Merchant details buyers pay into. Set these per environment.
AIRTEL_MONEY_BUSINESS_CODE = config("AIRTEL_MONEY_BUSINESS_CODE", default="")
AIRTEL_MONEY_ACCOUNT_NAME = config("AIRTEL_MONEY_ACCOUNT_NAME", default="Bitfuse")
TNM_MPAMBA_BUSINESS_CODE = config("TNM_MPAMBA_BUSINESS_CODE", default="")
TNM_MPAMBA_ACCOUNT_NAME = config("TNM_MPAMBA_ACCOUNT_NAME", default="Bitfuse")

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]
CORS_ALLOWED_ORIGINS = [
    "https://bitfuse-mw.vercel.app",
    "http://localhost:3000",
    "http://localhost:5173",
]
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# File storage (MinIO / S3-compatible or fallback to local)
# https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html

import os

# Check if we should use S3 or fallback to local storage
USE_S3 = config("USE_S3", default=False, cast=bool)

if USE_S3:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = config("AWS_S3_ENDPOINT_URL")
    AWS_S3_FILE_OVERWRITE = False
else:
    # Use local file storage for development
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": os.path.join(BASE_DIR, "media"),
            },
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
AWS_DEFAULT_ACL = None
AWS_S3_ADDRESSING_STYLE = "path"  # needed for MinIO


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

# Email Configuration
EMAIL_BACKEND = config("EMAIL_BACKEND", default="django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="Bitfuse <noreply@bitfuse.app>")

# SMS & OTP Configuration
SMS_PROVIDER = config("SMS_PROVIDER", default="console")  # Options: console, africas_talking, twilio
SMS_API_KEY = config("SMS_API_KEY", default="")
SMS_API_SECRET = config("SMS_API_SECRET", default="")
SMS_SENDER_ID = config("SMS_SENDER_ID", default="Bitfuse")

# CAPTCHA Configuration
CAPTCHA_ENABLED = config("CAPTCHA_ENABLED", default=False, cast=bool)
CAPTCHA_PROVIDER = config("CAPTCHA_PROVIDER", default="turnstile")  # Options: turnstile, recaptcha
CAPTCHA_SECRET_KEY = config("CAPTCHA_SECRET_KEY", default="")

# Google OAuth Configuration
GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = config("GOOGLE_CLIENT_SECRET", default="")
