# Generated by Django 4.2.7 on 2026-07-31 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_wallet"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ledger_id", models.CharField(max_length=100)),
                ("mwk_float_balance_id", models.CharField(max_length=100)),
                ("usdt_float_balance_id", models.CharField(max_length=100)),
                ("mwk_external_contra_id", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Platform Account",
                "verbose_name_plural": "Platform Account",
            },
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buy_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="MWK charged per 1 USDT bought",
                        max_digits=10,
                    ),
                ),
                (
                    "sell_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="MWK paid per 1 USDT sold",
                        max_digits=10,
                    ),
                ),
                (
                    "buy_fee_percent",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "sell_fee_percent",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Buy", "Buy"), ("Sell", "Sell")], max_length=10
                    ),
                ),
                ("amount_usdt", models.DecimalField(decimal_places=6, max_digits=18)),
                ("amount_mwk", models.DecimalField(decimal_places=2, max_digits=18)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Pending", "Pending"),
                            ("Cancelled", "Cancelled"),
                            ("Disputed", "Disputed"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("Airtel Money", "Airtel Money"),
                            ("TNM Mpamba", "TNM Mpamba"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("reference", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
