# Generated by Django 6.0.7 on 2026-08-03 21:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_platformaccount_rate_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="platformaccount",
            name="usdt_external_contra_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="platformaccount",
            name="usdt_frozen_balance_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="blnk_ledger_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
