# Generated by Django 6.0.7 on 2026-10-08 11:58

from django.db import migrations, models


def convert_empty_phone_numbers_to_null(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(phone_number="").update(phone_number=None)


def convert_null_phone_numbers_to_empty(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(phone_number__isnull=True).update(phone_number="")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_usersession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, default=None, max_length=20, null=True, unique=True
            ),
        ),
        migrations.RunPython(
            convert_empty_phone_numbers_to_null,
            reverse_code=convert_null_phone_numbers_to_empty,
        ),
    ]
