# Generated by Django 6.0.7 on 2026-10-08 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneotp",
            name="last_sent_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="provider_batch_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="send_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("verified", "Verified"),
                    ("expired", "Expired"),
                    ("failed", "Failed"),
                    ("superseded", "Superseded"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="phoneotp",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
